### ISSUE TITLE
请问这个是与原作者的you-get同步的吗？

### ISSUE THREAD

**Issue by xsjqqq123** [sceext2/you_get#1]
在https://github.com/soimort/you-get/issues/529 看到您的回复，由于我对python不了解，打算用您的这个当后台做解析用，现在拿不定主意的是，您这个的解析算法,是与原作保持同步的吗？

或者，有没有类似you-get ，但更新更及时的开源项目？

**Comment by sceext2** [comment]
有一段时间没有更新了 ;-)

我感觉 you-get 的代码结构, 不适合改造出 json 格式输出. 
you-get 是主程序调用每个网站的解析模块, 解析模块内部再反过来调用下载程序. 
you-get 是解析下载一体化的程序, 解析和下载结合的太紧密, 不好处理. 

其实我改造的 json 格式输出, 工作也不稳定. 
再加上 you-get 部分解析算法过时, 无法使用, 特别是我感兴趣的几个网站, 比如 iqiyi 等. you-get 不支持. 
所以就暂时没有更新. :-)

可以试试我写的另外 2 个程序:

parse_video <https://github.com/sceext2/parse_video>
+ 支持 iqiyi

evparse <https://github.com/sceext2/evparse/tree/version>
+ 支持 sohu
+ 支持 pptv
+ 支持 芒果tv

parse_video 和 evparse 都是 python3 写的, 都是只有解析功能, 并且输出 json 格式. 
自我感觉 parse_video 和 evparse 工作比较稳定. 缺点是支持网站太少. :-)

另外一个项目是 youtube-dl <https://github.com/rg3/youtube-dl>
这个支持很多网站, 并且直接有选项可以输出 json 格式. 
但是 youtube-dl 对 中国 的主流视频网站支持不好. 

另外, 有个网站, <http://www.flvsp.com/> 是一个 大神 写的, 功能很强大, 支持很多网站的解析. 
对 中国 主流视频网站支持很好, 比如 
 优酷网 土豆网 搜狐视频 芒果TV 腾讯视频 乐视网 PPS影音 PPTV 酷6网 56网 风行网 迅雷看看 暴风影音

你可以考虑从网页上抓取解析结果. (其实我就在这么干. :-)

实在不行, 可以考虑自己写 解析. 其实并不是很困难. ;-)

**Comment by xsjqqq123** [comment]
我考虑用http://www.flvsp.com/，发了封邮件给站长索要API了。我写的程序是qml为主的，本来打算自己用javascript写插件式的解析，可以实现。但既然有大神搞解析，我就厚着脸皮拿来用好了。

**Comment by sceext2** [comment]
Good luck to you. ;-)
